name: Update ConfigMap in Another Repo

on:
  workflow_dispatch:
    inputs:
      config_data:
        description: 'Enter key-value pair in the format {"key1":"value1","key2":"value2"}'
        required: true
        type: string
      configmap_path:
        description: 'Path to configmap'
        required: true
        type: string

jobs:
  update-configmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Survey repository
        uses: actions/checkout@v2
        with:
          repository: 'Karunakar1Reddy/survey'
          token: ${{ secrets.PAT_TOKEN }}
          ref: master

      - name: Checkout Test repository
        uses: actions/checkout@v2
        with:
          repository: 'Karunakar1Reddy/Test'
          token: ${{ secrets.PAT_TOKEN }}
          path: Test
          ref: main

      - name: Parse JSON input and update configmap.yaml
        run: |
          echo "Parsing input and updating configmap.yaml..."
          CONFIG_DATA='${{ github.event.inputs.config_data }}'
          CONFIGMAP_PATH='Test/${{ github.event.inputs.configmap_path }}'
          echo "ConfigMap Path: $CONFIGMAP_PATH"
          echo "Config Data: $CONFIG_DATA"
          # Convert JSON string to key-value pairs and update the configmap.yaml
          echo "$CONFIG_DATA" | jq -r 'to_entries | .[] | "\(.key): \(.value)"' | \
          while IFS=: read -r key value; do
            # Trim leading and trailing whitespace from key and value
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | xargs)

            # Check if the key is not empty
            if [ ! -z "$key" ]; then
              # Check if the key exists in the configmap.yaml file
              if grep -q "^$key:" "$CONFIGMAP_PATH"; then
                # Key exists, update its value
                sed -i "s/^$key:.*/$key: \"$value\"/" "$CONFIGMAP_PATH"
              else
                # Key does not exist, add it to the configmap.yaml file
                echo "$key: \"$value\"" >> "$CONFIGMAP_PATH"
              fi
            fi
          done

          cat "$CONFIGMAP_PATH"

      - name: Commit changes
        run: |
          cd Test
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          CONFIGMAP_PATH='${{ github.event.inputs.configmap_path }}'
          git add $CONFIGMAP_PATH
          git commit -m "Update configmap by ${{ github.actor }}"
          git push

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.PAT_TOKEN }}
          pr_title: "Update ConfigMap by ${{ github.actor }}"
          pr_body: "This PR updates the ConfigMap with the latest changes."

      - name: Notify dedicated teams channel
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Your custom notification message"
          notification-color: "17a2b8"
          timezone: "America/Denver"
          verbose-logging: true
