name: Add/Update ConfigMap in another repo

on:
  workflow_dispatch:
    inputs:
      config_data:
        description: 'Enter key-value pair in the format {"key1":"value1","key2":"value2"}'
        required: true
        type: string
      configmap_path:
        description: 'Path to configmap'
        required: true
        type: string

jobs:
  update-configmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Survey repository
        uses: actions/checkout@v2
        with:
          repository: 'Karunakar1Reddy/survey'
          token: ${{ secrets.PAT_TOKEN }}
          ref: master

      - name: Parse JSON input and update configmap.yaml
        run: |
          echo "Parsing input and updating configmap.yaml..."
          CONFIG_DATA='${{ github.event.inputs.config_data }}'
          CONFIGMAP_PATH='${{ github.event.inputs.configmap_path }}'
          echo "ConfigMap Path: $CONFIGMAP_PATH"
          cat $CONFIGMAP_PATH
          # Your existing script to update the configmap
          echo "Updated ConfigMap:"
          cat $CONFIGMAP_PATH

      - name: Commit changes
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git add .
          git commit -m "Update configmap by ${{ github.actor }}"
          git push

      - name: Checkout Test repository
        uses: actions/checkout@v2
        with:
          repository: 'Karunakar1Reddy/Test'
          token: ${{ secrets.PAT_TOKEN }}
          ref: main

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.PAT_TOKEN }}
          pr_title: "Update ConfigMap by ${{ github.actor }}"
          pr_body: "This PR updates the ConfigMap with the latest changes."

      - name: Notify dedicated teams channel
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Your custom notification message"
          notification-color: "17a2b8"
          timezone: "America/Denver"
          verbose-logging: true
